apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: security-service
    app.kubernetes.io/part-of: advancia-services
  annotations:
    argocd-image-updater.argoproj.io/image-list: security-service=032474760584.dkr.ecr.us-east-1.amazonaws.com/security-service
    argocd-image-updater.argoproj.io/security-service.update-strategy: semver
    argocd-image-updater.argoproj.io/security-service.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/security-service.write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: "git@github.com:your-org/infra.git"
    targetRevision: HEAD
    path: "k8s/overlays/prod/services/security-service"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
